# Generated by Django 3.1.7 on 2021-03-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.FileField(upload_to='', verbose_name='Initial file')),
                ('result', models.FileField(upload_to='', verbose_name='Result file')),
                ('bubble', models.CharField(max_length=1000, verbose_name='BubbleSort time')),
                ('optimized_bubble', models.CharField(max_length=1000, verbose_name='Optimized BubbleSort time')),
                ('insertion', models.CharField(max_length=1000, verbose_name='Insertion time')),
                ('merge', models.CharField(max_length=1000, verbose_name='Merge time')),
            ],
        ),
    ]
