# Generated by Django 3.1.7 on 2021-03-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorts', '0002_auto_20210302_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='sort',
            name='speed',
            field=models.CharField(default='', max_length=100, verbose_name='Execution time'),
        ),
    ]
