# Generated by Django 3.1.7 on 2021-03-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorts', '0003_sort_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort',
            name='type',
            field=models.CharField(choices=[('Bubble sort', 'Bubble sort'), ('Optimized Bubble sort', 'Optimized Bubble sort'), ('Insertion sort', 'Insertion sort'), ('Merge sort', 'Merge sort')], default='', max_length=100, verbose_name='Type'),
        ),
    ]
