# Generated by Django 3.1.7 on 2021-03-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorts', '0005_auto_20210302_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort',
            name='initial',
            field=models.FileField(upload_to='media/', verbose_name='Initial file'),
        ),
    ]
