# Generated by Django 3.1.7 on 2021-03-02 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorts', '0009_auto_20210302_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sort',
            name='result',
            field=models.FileField(default='', upload_to='task/media/', verbose_name='Result file'),
        ),
    ]
