# Generated by Django 3.1.7 on 2021-03-03 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorts', '0011_auto_20210302_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sort',
            name='speed',
        ),
    ]
